# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shashwat Shivam
title: Final Year, Computer Science and Engineering, IIT Delhi
email: shivamshaswat@gmail.com
website: https://ankurshaswat.github.io/

# Social links
twitter_username: ankurshaswat
github_username:  ankurshaswat
# dribbble_username: jekyll
facebook_username: ankurshaswat
# flickr_username: jekyll
instagram_username: ankurshaswat
linkedin_username: ankurshaswat
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, i am Shashwat, a final year undergraduate student at Computer Science and Engineering department , IIT Delhi. I have experience in data science projects along with creating software and web apps. I have worked on a number of projects with various groups picking up teamwork and software skills along the way. I am a tech enthusiast who likes creating new things and experimenting with things. 

  Download my CV by clicking <a target="_blank" href="./assets/ShashwatShivamCV.pdf">here</a>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Scholastic Achievements:
    - Secured <mark>All India Rank 82</mark> in Joint Entrance Exam Advanced - 2016 among 200 Thousand candidates.
    - Won <mark>IITD Semester Merit Award</mark> in first 2 semesters (given to top 7% of all the students).
    - Ranked in <mark>Top 0.01%</mark> among 2 million candidates appearing in Joint Entrance Examination(JEE Mains-2016).
    - Qualified <mark>KVPY</mark> Exam in ‘Kishore Vaigyanik Protsahan Yojana’ by Indian Institute of Science given to top 1%.
    - Became a National Talent Search Examination (<mark>NTSE</mark>) scholar for being in top 1000 at National level in 2014.
    - Ranked in Top 1% in India in <mark>NSEP</mark>,<mark>NSEC</mark> and <mark>NSEA</mark> (National Standard Examinations).
    - Awarded <mark>Student of The Year</mark> on graduating Higher Secondary for excellent academic performance.

  Extra Curricular Activites:
    - Received Honorable Mention at <mark>OpenEd AI Hackathon</mark> 2017 for creating NER using CRF for Hindi language.
    - Ranked in <mark>Top 3</mark> in <mark>Microsoft Code.fun.do online hackathon 2018</mark> for building an <mark>attention tracking application</mark>.
    - <mark>Microsoft Student Partner</mark> (August 2017 - October 2019)
    - Member of Robotics Club IIT Delhi (October 2016 - March 2017)
  
  Positions of Responsibilities:
    - Elected <mark>Manager</mark> at <mark>DevClub IIT Delhi</mark> (April 2019 - Present)
    - Executive <mark>Member</mark> & <mark>Developer</mark> at <mark>DevClub IIT Delhi</mark> (April 2018 - Present)

  Alongside my interests mentioned above some of my other interests and hobbies are:
   - Travelling
   - Reading
   - Watching Movies & TV series.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
