# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Shashwat Shivam
title: Final Year, Computer Science and Engineering, IIT Delhi
email: shivamshaswat@gmail.com
website: https://ankurshaswat.github.io/

# Social links
twitter_username: ankurshaswat
github_username:  ankurshaswat
# dribbble_username: jekyll
facebook_username: ankurshaswat
# flickr_username: jekyll
instagram_username: ankurshaswat
linkedin_username: ankurshaswat
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, i am Shashwat, a final year undergraduate student at Computer Science and Engineering department , IIT Delhi. I have experience in data science projects along with creating software and web apps. I have worked on a number of projects with various groups picking up teamwork and software skills along the way. I am a tech enthusiast who likes creating new things and experimenting with things. 

  Download my CV by clicking <a target="_blank" href="./assets/ShashwatShivamCV.pdf">here</a>.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Scholastic Achievements:
    - Secured All India Rank 82 in Joint Entrance Exam Advanced - 2016 among 200 Thousand candidates.
    - Won IITD Semester Merit Award in first 2 semesters (given to top 7% of all the students).
    - Ranked in Top 0.01% among 2 million candidates appearing in Joint Entrance Examination(JEE Mains-2016).
    - Qualified KVPY Exam in ‘Kishore Vaigyanik Protsahan Yojana’ by Indian Institute of Science given to top 1%.
    - Became a National Talent Search Examination (NTSE) scholar for being in top 1000 at National level in 2014.
    - Ranked in Top 1% in India in NSEP,NSEC and NSEA (National Standard Examinations).
    - Awarded Student of The Year on graduating Higher Secondary for excellent academic performance.

  Courses Done: Computer Vision, Reinforcement Learning, Natural Language Processing, Artificial Intelligence, Analysis & Design of Algorithms, Computer Networks, Data Structures & Algorithms, Discrete Mathematical Structures, Probability & Stochastic Pro., Computer Architecture, Programming Languages, Design Practices.
  
  Technical Skills:
    - Languages: C, C++, Python, Java, JavaScript, NodeJS, VHDL, PHP, OCaml, Prolog.
    - Environments: Git, Android Studio, LaTeX, Xilinx ISE Design Suite, Vivado.
    - Frameworks: PyTorch, TensorFlow, Django, Bootstrap, JQuery, MongoDB, MySQL.

  Extra Curricular Activites:
    - Received Honorable Mention at OpenEd AI Hackathon 2017 for creating NER using CRF for Hindi language.
    - Ranked in Top 3 in Microsoft Code.fun.do online hackathon 2018 for building an attention tracking application.
    - Microsoft Student Partner (August 2017 - October 2019)
    - Member of Robotics Club IIT Delhi (October 2016 - March 2017)
  
  Positions of Responsibilities:
    - Elected Manager at DevClub IIT Delhi (April 2019 - Present)
    - Executive Member & Developer at DevClub IIT Delhi (April 2018 - Present)

  Alongside my interests mentioned above some of my other interests and hobbies are:
   - Travelling
   - Reading
   - Watching Movies & TV series.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
